import type { Ratio } from "@repo/core";

/** Snapshot generated by packages/core computeRatios over aapl-companyfacts.json. */
export const aaplRatios = [
  {
    id: "revenue",
    label: "Revenue",
    value: 416_161_000_000,
    unit: "usd",
    period: "FY2025",
    sourceConcepts: ["RevenueFromContractWithCustomerExcludingAssessedTax"],
  },
  {
    id: "revenue-growth",
    label: "Revenue growth",
    value: 0.0642551178283274,
    unit: "percent",
    period: "FY2025",
    sourceConcepts: ["RevenueFromContractWithCustomerExcludingAssessedTax"],
  },
  {
    id: "gross-margin",
    label: "Gross margin",
    value: 0.4690516410716045,
    unit: "percent",
    period: "FY2025",
    sourceConcepts: [
      "RevenueFromContractWithCustomerExcludingAssessedTax",
      "CostOfGoodsAndServicesSold",
    ],
  },
  {
    id: "net-income",
    label: "Net income",
    value: 112_010_000_000,
    unit: "usd",
    period: "FY2025",
    sourceConcepts: ["NetIncomeLoss"],
  },
  {
    id: "net-margin",
    label: "Net margin",
    value: 0.2691506412181824,
    unit: "percent",
    period: "FY2025",
    sourceConcepts: [
      "NetIncomeLoss",
      "RevenueFromContractWithCustomerExcludingAssessedTax",
    ],
  },
  {
    id: "cash",
    label: "Cash",
    value: 35_934_000_000,
    unit: "usd",
    period: "FY2025",
    sourceConcepts: ["CashAndCashEquivalentsAtCarryingValue"],
  },
  {
    id: "runway",
    label: "Runway",
    value: null,
    unit: "months",
    period: "FY2025",
    sourceConcepts: [
      "CashAndCashEquivalentsAtCarryingValue",
      "NetCashProvidedByUsedInOperatingActivities",
    ],
    note: "Operating cash flow is positive for FY2025, so the company has no cash burn.",
  },
  {
    id: "liabilities-to-assets",
    label: "Liabilities / assets",
    value: 0.7947533828265705,
    unit: "ratio",
    period: "FY2025",
    sourceConcepts: ["Liabilities", "Assets"],
  },
] satisfies Ratio[];
