import type {
  Company,
  FilingRef,
  RefusalReason,
  Result,
  Section,
  SectionId,
  Signal,
  Tearsheet,
} from "@repo/core";
import rawFiling from "../../../fixtures/aapl-10k-sections.json";
import { aaplRatios } from "../fixtures/aapl-ratios";

export type RatiosData = Pick<Tearsheet, "company" | "filing" | "ratios">;
export type SignalsData = Pick<Tearsheet, "filing" | "sections" | "signals">;

const company: Company = rawFiling.company;
const filing: FilingRef = rawFiling.filing;

function isSectionId(value: string): value is SectionId {
  return value === "risk-factors" || value === "mdna";
}

const sections: Section[] = rawFiling.sections.flatMap((section) => {
  if (!isSectionId(section.id)) {
    return [];
  }

  return [{ ...section, id: section.id }];
});

const signalFixture = [
  {
    claim: "Trade restrictions could disrupt Apple’s business and supply chain.",
    category: "risk",
    quote:
      "Restrictions on international trade, such as tariffs and other controls on imports or exports of goods, technology or data, can materially adversely affect the Company’s business and supply chain.",
    locator: { sectionId: "risk-factors", offset: 23_636 },
  },
  {
    claim:
      "Aggressive pricing is putting pressure on gross margins across Apple’s markets.",
    category: "red-flag",
    quote:
      "These markets are characterized by aggressive price competition, downward pressure on gross margins, continual improvement in product performance, and price sensitivity on the part of consumers and businesses.",
    locator: { sectionId: "risk-factors", offset: 30_023 },
  },
  {
    claim:
      "Services growth is being driven by advertising, the App Store and cloud services.",
    category: "strategy",
    quote:
      "Services Services net sales increased during 2025 compared to 2024 primarily due to higher net sales from advertising, the App Store and cloud services.",
    locator: { sectionId: "mdna", offset: 104_797 },
  },
  {
    claim:
      "Management says existing liquidity, operating cash generation and debt access can cover cash requirements.",
    category: "financial-health",
    quote:
      "Liquidity and Capital Resources The Company believes its balances of cash, cash equivalents and marketable securities, which totaled $132.4 billion as of September 27, 2025, along with cash generated by ongoing operations and continued access to debt markets, will be sufficient to satisfy its cash requirements and capital return program over the next 12 months and beyond.",
    locator: { sectionId: "mdna", offset: 108_419 },
  },
] satisfies Signal[];

function normalizeTicker(ticker: string): string {
  return ticker.trim().toUpperCase();
}

function unavailableFixture<T>(ticker: string): Result<T> {
  const normalizedTicker = normalizeTicker(ticker);
  return refusal(
    "unknown-ticker",
    `${normalizedTicker || "That ticker"} is not present in the committed preview fixture. Try AAPL.`,
  );
}

function success<T>(data: T): Result<T> {
  return { ok: true, data };
}

function refusal<T>(reason: RefusalReason, message: string): Result<T> {
  return { ok: false, refusal: { reason, message } };
}

function isVerbatimSignal(signal: Signal): boolean {
  const sourceSection = sections.find(
    (section) => section.id === signal.locator.sectionId,
  );
  if (!sourceSection) {
    return false;
  }

  const { offset } = signal.locator;
  return sourceSection.text.slice(offset, offset + signal.quote.length) === signal.quote;
}

/**
 * Fixture seam for deterministic figures. The snapshot was produced by core
 * from committed XBRL facts; issue #5 replaces it with the live core call.
 */
export async function getRatios(ticker: string): Promise<Result<RatiosData>> {
  if (normalizeTicker(ticker) !== company.ticker) {
    return unavailableFixture(ticker);
  }

  return success({ company, filing, ratios: aaplRatios });
}

/**
 * Fixture seam for grounded prose. The pause makes the required Suspense phase
 * visible in preview; live extraction replaces it in issue #5.
 */
export async function getSignals(ticker: string): Promise<Result<SignalsData>> {
  if (normalizeTicker(ticker) !== company.ticker) {
    return unavailableFixture(ticker);
  }

  if (process.env.NODE_ENV !== "test") {
    await new Promise<void>((resolve) => setTimeout(resolve, 1_200));
  }

  const signals = signalFixture.filter(isVerbatimSignal);
  if (signals.length === 0) {
    return refusal(
      "section-not-found",
      "No grounded signal in the preview fixture could be traced to an exact filing span.",
    );
  }

  return success({ filing, sections, signals });
}
